version: '3'
services:
  app:
    build: .
    ports:
      - 6000:5000
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: flaskapp
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

